### ISSUE TITLE
Convert caffe model to PyTorch model

### ISSUE THREAD

**Issue by busning** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#10]
When I run the last command to convert caffe model to pytorch model: "mmtomodel -f pytorch -in Pytorch_VGGFACE_IR.py -iw Pytorch_VGGFACE_IR.npy -o Pytorch_VGGFACE.pth", I met the following problem: 

Traceback (most recent call last):
  File "/root/anaconda3/bin/mmtomodel", line 10, in <module>
    sys.exit(_main())
  File "/root/anaconda3/lib/python3.7/site-packages/mmdnn/conversion/_script/dump_code.py", line 79, in _main
    ret = dump_code(args.framework, args.inputNetwork, args.inputWeight, args.outputModel, args.dump_tag)
  File "/root/anaconda3/lib/python3.7/site-packages/mmdnn/conversion/_script/dump_code.py", line 32, in dump_code
    save_model(MainModel, network_filepath, weight_filepath, dump_filepath)
  File "/root/anaconda3/lib/python3.7/site-packages/mmdnn/conversion/pytorch/saver.py", line 5, in save_model
    model = MainModel.KitModel(weight_filepath)
  File "Pytorch_VGGFACE_IR.py", line 27, in __init__
    self.conv1_1 = self.__conv(2, name='conv1_1', in_channels=3, out_channels=64, kernel_size=(3, 3), stride=(1, 1), groups=1, bias=True)
  File "Pytorch_VGGFACE_IR.py", line 129, in __conv
    layer.state_dict()['bias'].copy_(torch.from_numpy(__weights_dict[name]['bias']))
RuntimeError: output with shape [64] doesn't match the broadcast shape [1, 1, 1, 64]

Any ideas to solve this problem?

**Comment by busning** [comment]
Instead of using "pip install mmdnn", I used "pip install -U git+https://github.com/SmokerX/MMdnn.git@skydata". This is because I met an error "ModuleNotFoundError: No module named 'caffe'", and I got a solution in "https://github.com/microsoft/MMdnn/issues/566".

In addition, I used ubuntu 18.04, Cuda 10.0, tried different versions of pytorch 0.4.1, 1.0, 1.1. Is it possible that you share a link to download the "Pytorch_VGGFACE_IR.py and Pytorch_VGGFACE.pth" files? Thank you in advance.

**Comment by chervonij** [comment]
@busning 
https://drive.google.com/file/d/1--H-BwwZhjE4USGIQEfo0jLauA7UDNfD/view?usp=sharing

**Comment by busning** [comment]
@chervonij Thank you so much for your quick response!

**Comment by sunwoo76** [comment]
> Instead of using "pip install mmdnn", I used "pip install -U git+https://github.com/SmokerX/MMdnn.git@skydata". This is because I met an error "ModuleNotFoundError: No module named 'caffe'", and I got a solution in "[microsoft/MMdnn#566](https://github.com/microsoft/MMdnn/issues/566)".
> 
> In addition, I used ubuntu 18.04, Cuda 10.0, tried different versions of pytorch 0.4.1, 1.0, 1.1. Is it possible that you share a link to download the "Pytorch_VGGFACE_IR.py and Pytorch_VGGFACE.pth" files? Thank you in advance.



> When I run the last command to convert caffe model to pytorch model: "mmtomodel -f pytorch -in Pytorch_VGGFACE_IR.py -iw Pytorch_VGGFACE_IR.npy -o Pytorch_VGGFACE.pth", I met the following problem:
> 
> Traceback (most recent call last):
> File "/root/anaconda3/bin/mmtomodel", line 10, in
> sys.exit(_main())
> File "/root/anaconda3/lib/python3.7/site-packages/mmdnn/conversion/_script/dump_code.py", line 79, in _main
> ret = dump_code(args.framework, args.inputNetwork, args.inputWeight, args.outputModel, args.dump_tag)
> File "/root/anaconda3/lib/python3.7/site-packages/mmdnn/conversion/_script/dump_code.py", line 32, in dump_code
> save_model(MainModel, network_filepath, weight_filepath, dump_filepath)
> File "/root/anaconda3/lib/python3.7/site-packages/mmdnn/conversion/pytorch/saver.py", line 5, in save_model
> model = MainModel.KitModel(weight_filepath)
> File "Pytorch_VGGFACE_IR.py", line 27, in **init**
> self.conv1_1 = self.__conv(2, name='conv1_1', in_channels=3, out_channels=64, kernel_size=(3, 3), stride=(1, 1), groups=1, bias=True)
> File "Pytorch_VGGFACE_IR.py", line 129, in __conv layer.state_dict()['bias'].copy_(torch.from_numpy(__weights_dict[name]['bias']))
> RuntimeError: output with shape [64] doesn't match the broadcast shape [1, 1, 1, 64]
> 
> Any ideas to solve this problem?

Did you solve this problem?
I have the same problem!

**Comment by sunwoo76** [comment]
> @busning
> https://drive.google.com/file/d/1--H-BwwZhjE4USGIQEfo0jLauA7UDNfD/view?usp=sharing

Thank you.
But, your comment is quite long. I want to check this is the caffe trained model or not.
Is the caffe trained model weight?

Thanks! :)

**Comment by phquanta** [comment]
> @busning
> https://drive.google.com/file/d/1--H-BwwZhjE4USGIQEfo0jLauA7UDNfD/view?usp=sharing

Your VGGFace is not original VGGFace (1000 labels 2622 in original VGGface, and 19 layers vs 16 original)
