### ISSUE TITLE
Regarding Question about discriminator last layer

### ISSUE THREAD

**Issue by akshay951228** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#13]
hi,
there is no activation function at end of discriminator
https://github.com/vincent-thevenin/Realistic-Neural-Talking-Head-Models/blob/master/network/model.py#L246

Is there any reason not putting activation(sigmod,tanh)?

**Comment by vincent-thevenin** [comment]
You could use tanh at the end of discriminator to keep the output between -1 and 1. I used it at the beginning but I had a problem with vanishing gradient, so I had to roll back. The code changed a lot since so it should be okay to put a tanh back to test it out.

**Comment by vincent-thevenin** [comment]
Hmm upon reconsidering the question I realized I was very wrong. The last layers of the discriminator uses an affine parameter so we do indeed need a final activation function. Thank you for opening your issue @akshay951228 . I will add a scaled tanh at the end.
