### ISSUE TITLE
Bilinear Down/Upsampling

### ISSUE THREAD

**Issue by Connor323** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#15]
Thanks a lot for the great efforts! 

Although the Samsung paper didn't mention the interpolation method, according to the style-gan paper, they actually used bilinear interpolation for up/downsampling operations. When I train using your code, I have seen the checkerboard effect a lot especially in the early training stage. Have you considered using the bilinear interpolation method for the upsampling function?

**Comment by mrgloom** [comment]
Looks like `nn.Upsample` use `nearest` upsampling algorithm by default.
https://pytorch.org/docs/stable/_modules/torch/nn/modules/upsampling.html

https://github.com/vincent-thevenin/Realistic-Neural-Talking-Head-Models/blob/0c9b470242502246e94b1a3d2c60f1750f8535be/network/blocks.py#L153

**Comment by Connor323** [comment]
Correct! And I have been testing changing it to bilinear interpolation. It seems it removes the  checkerboard effect, but introduces a ringing effect. lol I'm still working on it.

**Comment by mrgloom** [comment]
What do you mean by 'ringing effect'? can you show example image?

**Comment by Connor323** [comment]
This is the checkerboard effect I got using default nearest interpolation: 
![individualImage-12](https://user-images.githubusercontent.com/12059991/64368543-8effc580-cfe8-11e9-9e9e-7ec0040e70c5.png)

This is the ringing effect I got using bilinear interpolation: 
![individualImage-15](https://user-images.githubusercontent.com/12059991/64368480-6bd51600-cfe8-11e9-9a89-3960657024fa.png)

**Comment by vincent-thevenin** [comment]
Looks like the ringing effect is somewhat less noticeable than the checkerboard one. If you'd like to do a pull request go ahead :)
The effect should die out eventually with more training.
