### ISSUE TITLE
About generating images

### ISSUE THREAD

**Issue by LWei-gfkd** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#17]
According to the provided source code and weight, using the VoxCeleb2 test set for training, the image generation is not good, and the image details are seriously lost. How long do you train to get the training effect in the example you provided?

**Comment by vincent-thevenin** [comment]
I trained for 5 epochs so far. This is not optimal according to the source paper (should be 75 epochs on full dataset that is 10 times larger).

**Comment by LWei-gfkd** [comment]
Are the weights you provided trained with the test set of voxceleb2? Why do I run your code directly, the loss value becomes very large immediately (the value of the vggface part of the lossCNT is particularly large)

**Comment by vincent-thevenin** [comment]
Yes I trained with voxceleb2.
When was the last time you ran the training? It could be an error introduced Aug 11 in the gradient for vggface. I fixed that recently Sept 4 in a recent commit, could you update your local repo and tell me if there's any change?
