### ISSUE TITLE
About results

### ISSUE THREAD

**Issue by sbyNiceBlowJob** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#18]
Does your embedder work well? After training for 300+epochs, I find the embedder totally didn't work and the results only depend on the input of the generator.

**Comment by vincent-thevenin** [comment]
It should be working if the generated images has the same background and facial features or the person (e.g. beard, glasses, shirt...). Can you share some output you got during training?

**Comment by sbyNiceBlowJob** [comment]
Well, I don't know how to upload pictures... Does your result change when the input to the embedder changes?

**Comment by vincent-thevenin** [comment]
Yes it does on my side.
You can drag any images to the comment box and it will upload it to github.
Just to be sure are you training by running train.py? finetuning_training.py does not train the embedder.

**Comment by sbyNiceBlowJob** [comment]
![0000625](https://user-images.githubusercontent.com/29035441/64486258-413fc300-d25d-11e9-85b6-f099a0e9ba6d.jpg)
![0000675](https://user-images.githubusercontent.com/29035441/64486265-4c92ee80-d25d-11e9-9df1-a2d0d591742c.jpg)
![0000700](https://user-images.githubusercontent.com/29035441/64486267-56b4ed00-d25d-11e9-9441-4ca995a9e3bf.jpg)
![0000800](https://user-images.githubusercontent.com/29035441/64486269-5caace00-d25d-11e9-9207-f1c7de120a39.jpg)
The first col is the input, second is GT, third is the embedder image(I didn't use finetune), the fourth is the result. My results are always too similar to the GT while the embedder has little effect on it.
I used the train.py, but I made several modifications. First, I removed part of the generator(two ResDown and two ResUp so the number of parameters will match that mentioned in the paper, about 38M). Second, I used another VGG because while I run the code with the VGG you provided it always told me that my GPU is out of memory. Third, I didn't use different colors to draw the input. Finally, I only include 50 people with totally 17000+ images, which is far beyond the number in the original people. Have you got any idea why my embedder didn't work? Can you share some of your  results for the same generator input with different embedder inputs? Thanks a lot!

**Comment by vincent-thevenin** [comment]
It looks like the input for the embedder and the GT are not the same person or are not from the same video, am I correct?

**Comment by sbyNiceBlowJob** [comment]
Yes, you are right

**Comment by vincent-thevenin** [comment]
That would be a problem, the embedder will have a hard time learning to encode the background and characteristic of the person since there's no correlation with GT. During training you want to recreate the GT image so the embedder has to encode an image related to the Generator's input with the same person and background and clothing. The only difference between embedder input and generator input is that they have different facial positions.
