### ISSUE TITLE
numpy 1.16.1

### ISSUE THREAD

**Issue by IMJONEZZ** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#2]
I'm having an issue installing version 1.16.1. I'm getting an error stating that that version cannot be imported because it does not exist.

Is there no way to get the pickle working with 1.16.4?

**Comment by vincent-thevenin** [comment]
It's an issue on MMdnn's side https://github.com/Microsoft/MMdnn.
I can only suggest you try installing numpy 1.16.1 again, with `!pip install numpy==1.16.1`
