### ISSUE TITLE
How to use webcam inference for mp4

### ISSUE THREAD

**Issue by rexxar-liang** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#21]
Hi,
    I try to use webcam_inference.py to inference a mp4 and get every frame outputs(fake/me/landmarks), but I got all outputs in full black color.
    Process:
    1、download the pretrained model.
    2、run embedder_inference.py to get e_hat_images.tar
    3、modify  “cap = cv2.VideoCapture(0)” to “cap = cv2.VideoCapture(xxx.mp4)” in webcam_inference.py
    4、run webcam_inference.py to get outputs(fake/me/landmarks)
   
    Any suggestions? Thanks.

**Comment by HansonKuo** [comment]
Hi, 
It is possible that your image output values are at the scale between 0~1.
Since the brightest value of a color is 255, any value smaller than 1 would close to black.
Scale all out1, out2, out3 by 255 then you should see your results.
