### ISSUE TITLE
about requirements.txt

### ISSUE THREAD

**Issue by fastcode3d** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#22]
Can you provide a requirements.txt？

I'm trying to replicate this project,but there's a lack of environment, and I'm worried about potential bugs caused by version problems.

Maybe you can use pipreqs to generate requirements.txt
pip install pipreqs
pipreqs ./

**Comment by vincent-thevenin** [comment]
I uploaded the requirements.txt
