### ISSUE TITLE
Cannot decompress pretrained weights

### ISSUE THREAD

**Issue by asterisk37n** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#23]
Pretrained weights on Google Drive cannot be decompressed on MacOS Mojave

$ tar xvf model_weights.tar
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.

$ tar --version
bsdtar 2.8.3 - libarchive 2.8.3

**Comment by vincent-thevenin** [comment]
You don't need to decompress the weights file. It is loaded with the .tar extension in the code.
