### ISSUE TITLE
converted vgg face 

### ISSUE THREAD

**Issue by MengXinChengXuYuan** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#28]
Hi! Thank you for sharing your great work first!
Any possibility for sharing the converted vgg face model? Sorry but I got some inconvenience making the environment

**Comment by vincent-thevenin** [comment]
Hi!
Here are the links from my drive: 
https://drive.google.com/open?id=1ooUatULWoyGbc4iVYFI0EMZSwwJcWUaM
https://drive.google.com/open?id=1-07XaOnweINQLjTU63N9t6SJjls13otq
