### ISSUE TITLE
embedder_inference.py errors

### ISSUE THREAD

**Issue by tomljr2** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#29]
Hello,

I have followed all of the steps you outlined in the README and I believe everything is set up properly. When I try to run embedder_inference.py I just get a bunch of errors, like so:

Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
/home/tomljr2/UF/project/dataset/video_extraction_conversion.py:118: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig = plt.figure(figsize=(input.shape[1]/dpi, input.shape[0]/dpi), dpi = dpi)
Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
Error: Video corrupted or no landmarks visible
Traceback (most recent call last):
  File "embedder_inference.py", line 25, in <module>
    frame_mark_video = generate_cropped_landmarks(frame_mark_video, pad=50)
  File "/home/tomljr2/UF/project/dataset/video_extraction_conversion.py", line 151, in generate_cropped_landmarks
    frame_landmark_list.append(frame_landmark_list[i])
IndexError: list index out of range

Any idea what is causing this? 

Also if you could detail the flow of how you actually use the program once I've got it working, I would really appreciate it because I didn't see much in the README. 

Thanks!

**Comment by vincent-thevenin** [comment]
Hi @tomljr2 ,
I kust updated from README running example

    train.py: initialize and train the network or continue training from trained network
    embedder_inference.py: (Requires trained model) Run the embedder on videos or images of a person and get embedding vector in tar file
    fine_tuning_trainng.py: (Requires trained model and embedding vector) finetune a trained model
    webcam_inference.py: (Requires trained model and embedding vector) run the model using person from embedding vector and webcam input, just inference

Could you remove the try except in https://github.com/vincent-thevenin/Realistic-Neural-Talking-Head-Models/blob/d08a37be675295274981d37e9ca12bc6b2ba925f/dataset/video_extraction_conversion.py#L110 
The error that gets displayed may hold more info for debugging

**Comment by recong** [comment]
I ran into the same problem when I tried to run this program on my macbook. The error message was 
` figurecanvasmac objectmac object has no atribute renderer`
I solved it by adding 
`import matplotlib`
`matplotlib.use('Agg')`
to the beggining of the program.
If anyone is facing a similar problem, I'd appreciate it if you can help.
