### ISSUE TITLE
Instance normalization is used only in generator's downsampling

### ISSUE THREAD

**Issue by asterisk37n** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#30]
Seeing current implementation of this repository,  discriminator has instance normalization, but it is against architecture on the paper.

According to the paper,
> We base our generator network G(yi(t), eˆi; ψ, P) on the
image-to-image translation architecture proposed by Johnson et. al. [20], but replace downsampling and upsampling layers with residual blocks similarly to [6] (with batch normalization [16] replaced by instance normalization [38])

> ional part of the discriminator V (xi(t), yi(t); θ), we use similar networks, which consist of residual downsampling blocks (same as the ones used in the generator, but without normalization layers)

**Comment by vincent-thevenin** [comment]
You're correct. Thanks for pointing that out! I'll make the necessary changes.
