### ISSUE TITLE
Question for embedeer_inference.py

### ISSUE THREAD

**Issue by parkjh688** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#31]
Hi.

I'm a newbie of PyTorch.
I run the embedder_inference.py with new test image and your mp4 file.
But the code save only 2 tar files. How to check the result mp4 file from this code?

Thanks

**Comment by vincent-thevenin** [comment]
Once you have e_hat_video.tar or e_hat_images.tar, you can use either one for inference using the webcam or for finetuning training. These are just the vector output of the Embedder network.

**Comment by parkjh688** [comment]
Thanks I solved it!
