### ISSUE TITLE
Can't see any fake face 

### ISSUE THREAD

**Issue by parkjh688** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#32]
Hi.

I  run webcam_inference.py file and I got 3 windows which are fake, me, landmark.
But only me and landmarks show. Any fake face wasn't made.
How can I fix this?

**Comment by vincent-thevenin** [comment]
Hi @parkjh688 ,

I need more info: do you have my pretrained weights or you own trained weights? Did you run the embedder_inference to get the embedded vectors?

**Comment by parkjh688** [comment]
Oh I solved that problem with my trained weights! Thanks
