### ISSUE TITLE
caffe-cuda can't be installed on Ubuntu16

### ISSUE THREAD

**Issue by OldChi** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#36]
hi Vincent, thanks for your great contribution. 

I'm using Ubuntu16 and can't run "sudo apt install caffe-cuda"

the reason seems to be caffe-cuda is only supported on Ubuntu>17.04

could you please kindly tell me if there is some other way to replace "sudo apt install caffe-cuda"?

thank you very much!

**Comment by vincent-thevenin** [comment]
Hey, have you found a solution yet? Otherwise this may help:
[BVLC/Caffe on Ubuntu 16.04 with Cuda Toolkit 8.0.61-1, CUDNN library 7.0.2.38-1 and OpenCV version 2.x or 3.3](https://github.com/BVLC/caffe/wiki/Ubuntu-16.04-Installation-Guide)
