### ISSUE TITLE
Generating video for own image

### ISSUE THREAD

**Issue by vovaekb** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#39]
I see that embedder_inference.py and finetuning_training.py both use test image and video of a person in the fake. I would like to generate fake video for own image of a person using the only image, I have no video. How I can do it?

**Comment by Bip3** [comment]
The embedded inference is written to embed both a video file and a folder of image files at the same time into two seperate files. If you want to just embed an image file just alter the code a tad. either comment out the code to embed the video file or just create a function that runs the code on an inputed image or video file.
