### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by ak9250** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#4]
can you share your pretrained model and testing code

**Comment by vincent-thevenin** [comment]
Pasted a link in the ReadME to the eight files on my drive. Testing code coming soon.

**Comment by ak9250** [comment]
@vincent-thevenin thanks looking forward to the test code

**Comment by EricHallahan** [comment]
It looks like the file will not unarchive.
```shell
$ tar -xvf model_weights.tar
  tar: This does not look like a tar archive
  tar: Skipping to next header
```

**Comment by vincent-thevenin** [comment]
You don't need to unarchive it. You can use the path to the file as is.

**Comment by ak9250** [comment]
@vincent-thevenin currently inference is through webcam, is there a test for single image or multi image inputs?

**Comment by iyah4888** [comment]
It seems that webcam_inference.py requires "e_hat.tar", but it is not documented in anywhere.
Could you give some context and share the pre-trained model of e_hat?
Thanks!

**Comment by vincent-thevenin** [comment]
@ak9250 The class methods for finetuning are already coded in. I still need to write the code for training in finetuning mode, I will work on this.

**Comment by vincent-thevenin** [comment]
@iyah4888 "e_hat.tar" is an output of embedder network. You can run inference on the embedder on any picture and get an e_hat.

I will add some lines to explicitely create it thanks for reminding me!

**Comment by vincent-thevenin** [comment]
@ak9250 You can now train the network in finetuning mode on a single video or image. You have to run finetuning_training.py and change the paths in the file to the video or images you want to use.

**Comment by vincent-thevenin** [comment]
@iyah4888 You can now run embedder_inference.py to create your own embedding.
