### ISSUE TITLE
about training data samplers

### ISSUE THREAD

**Issue by maliho0803** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#42]
as original paper saied 'The generator G(yi(t); e^i; ; P) takes the landmark image yi(t) for the video frame not seen by the embedder,the predicted video embedding e^i and outputs a synthesized video frame x^i(t). ', however, in your dataloader part, the image used in generator was appeared in embedder?

**Comment by vincent-thevenin** [comment]
The dataloader loads all the data for the embedder, generator and discrimninator. In the training loop each network receives its proper input. e.g. `x_hat = G(g_y, e_hat)`

**Comment by Jarvisss** [comment]
@vincent-thevenin @maliho0803 
In the original paper, section 3.2, it is said the input to the generator is not used for the embedder

![image](https://user-images.githubusercontent.com/16323003/88371846-67177d00-cdc7-11ea-95e7-2185fc3e72b8.png)

But it seems that, in your dataloader, the input to the embedder is K images and K landmarks, while the input landmark to the generator is randomly picked from the K samples.
