### ISSUE TITLE
Weird results on example images

### ISSUE THREAD

**Issue by Ignotus** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#45]
Hello,

Thank you for sharing the code. I have tried to run it on example image from https://github.com/vincent-thevenin/Realistic-Neural-Talking-Head-Models/tree/master/examples/fine_tuning/test_images .

Even after fine tuning finetuning_training.py it produces quite strange not-realistic results with provided pretrained model:

![iTerm2 XcdeHl frame0000](https://user-images.githubusercontent.com/500773/76877825-4157f580-6874-11ea-90de-af59f648deb0.jpg)

Any idea what might goes wrong?

Thank you in advance.

**Comment by Bip3** [comment]
Looks like you’ve used the video e_hat to train on the example image. After you run embedder_inference.py, make sure the path_to_embedding variable in finetuning_training.py is the actual path to the embedded image file. By default it should be e_hat_images.

**Comment by Ignotus** [comment]
@Bip3  thank you for your response. path_to_embedding = 'e_hat_images.tar' in my case.

**Comment by Ignotus** [comment]
Seems like doesn't work if I fine tune on the testing images and then feed landmarks from the testing example video during inference time. Probably both landmarks and identity image should be in the training data, or landmark should not be different too much from it.

**Comment by lvZic** [comment]
I have met the same problem, while  i use mark zuckerberg's video as landmark  and testing example as embedding with pretrained model.
