### ISSUE TITLE
weird results on pretrained model

### ISSUE THREAD

**Issue by wmonica** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#49]
Thanks for your work!
I have tested the examples on the pretrained model. 
I run embedder_inference.py firstly, the second is finetuning_training.py, the third is video_inference.py.
However, the generated results are noise, which is not a face. Could you help me why this happened?

**Comment by wmonica** [comment]
![ccc](https://user-images.githubusercontent.com/4161303/83042094-d3019180-a073-11ea-9bd2-2f7923d82dfb.jpg)

**Comment by zyainfal** [comment]
I have seen the same problem, have you solved it?

**Comment by ahuirecome** [comment]
I met the same problem.
