### ISSUE TITLE
Generate Noises

### ISSUE THREAD

**Issue by zyainfal** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#52]
Hi, thanks for your work on reproducing this paper. 

During the test, I ran the embedder_inference.py, without fine-tuning, and ran video_inference.py 
but I got a noise output from models. 
![test](https://user-images.githubusercontent.com/28991072/88285446-aab7ab80-cd21-11ea-823f-ead0f9193a2e.JPG)

Any suggestions? Thanks!

**Comment by zhaoyuehrb** [comment]
Same here... Did you solve it? Thanks!

**Comment by zhaoyuehrb** [comment]
Remove the '*255' for out1 in video_reference.py near the end. Then the output will be normal. Cheers!

**Comment by zyainfal** [comment]
> Remove the '*255' for out1 in video_reference.py near the end. Then the output will be normal. Cheers!

Sorry for this late reply.
But it is great!
Cheers!
