### ISSUE TITLE
Where can I obtain e_hat.tar used in webcam demo?

### ISSUE THREAD

**Issue by s60912frank** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#6]

**Comment by imaxpayne** [comment]
Same question, can't find e_hat.tar..

**Comment by EricHallahan** [comment]
`e_hat.tar` is the embedding created from the input image. You should be able to create one using the `Embedder()` class.

**Comment by s60912frank** [comment]
> 
> 
> `e_hat.tar` is the embedding created from the input image(s). You should be able to create one using the `Embedder()` class.

Thank you! I am able to run it now.
