### ISSUE TITLE
Preliminary landmarks extraction

### ISSUE THREAD

**Issue by chervonij** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#7]
Hello!
Many thanks for your work.

One question. Are you planning to add preprocessing of landmarks? 
As far as I understand, now the extraction of landmarks occurs during training and this increases the time for batch (4.5 seconds for me). It would be more efficient to extract the landmarks once and then just load them during training.

**Comment by victormashkov19** [comment]
I think that it will be more efficient to use  the code of preliminary landmarks extraction like as https://github.com/grey-eye/talking-heads

**Comment by iyah4888** [comment]
What is the difference of this repository and the one you pointed (https://github.com/grey-eye/talking-heads)?

**Comment by vincent-thevenin** [comment]
@chervonij Hi!

That's an interesting idea. I will definitely work towards doing that if it can make training faster.

**Comment by chervonij** [comment]
@vincent-thevenin 
In my opinion, this will speed up the training at least 3-4 times. This will also solve the problem of OOM with a large dataset.

**Comment by chervonij** [comment]
@iyah4888 
The difference is that in that repository, frames and landmarks are extracted in advance and saved to files.
In addition, there is a different model architecture. I tested it and even after 10 epochs there are no good results.

**Comment by vincent-thevenin** [comment]
Preprocess added in preprocess.py, you can run it on the downloaded dataset and create a smaller one
